//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButiqueShops.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ButiqueShopsEntities : DbContext
    {
        public ButiqueShopsEntities()
            : base("name=ButiqueShopsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<ItemTypes> ItemTypes { get; set; }
        public virtual DbSet<UserLikedItem> UserLikedItem { get; set; }
        public virtual DbSet<UserLikeShop> UserLikeShop { get; set; }
        public virtual DbSet<UserVisitedShop> UserVisitedShop { get; set; }
        public virtual DbSet<UserVistedItem> UserVistedItem { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Sizes> Sizes { get; set; }
        public virtual DbSet<Items> Items { get; set; }
    }
}
