//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ButiqueShops.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsToSubmit
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ImagePath { get; set; }
        public string SmallImagePath { get; set; }
        public Nullable<int> ShopId { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual ItemTypes ItemTypes { get; set; }
    }
}
